dist: xenial   # required for Python >= 3.7
matrix:
  include:
    - language: python
      python:
        - '3.7'
      install:
        - pip install -r requirements.txt
        - mkdir -p brythonserver/static/brython
        - cd brythonserver/static/brython
        - python3 -m brython --update
      script:
        - ./scripts/run_tests.sh
    - language: node_js
      node_js:
        - 14
      install:
        - npm install standard --global
      script:
        - ./scripts/run_js_tests.sh
