name: on-push
on: [push]
jobs:
  test-build-and-linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install standard --global
      - run: run_js_tests.sh
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      - run: pip install -r requirements.txt  
      - run: mkdir -p brythonserver/static/brython
      - run: pushd brythonserver/static/brython
      - run: brython-cli install
      - run: popd
      - run: ./scripts/run_tests.sh